### ISSUE TITLE
Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

### ISSUE THREAD

**Issue by Prudvi01** [josh-ashkinaze/Normalized-Google-Distance#1]
I'm getting this output no matter how many times I try:
![Screenshot 2020-03-29 at 1 35 41 PM](https://user-images.githubusercontent.com/29304096/77844204-31200e80-71c2-11ea-8d79-6a49b06e4b82.jpg)

**Comment by LinqLover** [comment]
Installing `lxml` solves that problem.

However, the next error is coming soon:
```
'NoneType' object has no attribute 'text'
Trying again...
'NoneType' object has no attribute 'text'
Trying again...
```

**Comment by Prudvi01** [comment]
Closing this issue and referencing the new issue
