### ISSUE TITLE
'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by greysou1** [josh-ashkinaze/Normalized-Google-Distance#3]
Installing `lxml` solves that problem.

However, the next error is coming soon:
```
'NoneType' object has no attribute 'text'
Trying again...
'NoneType' object has no attribute 'text'
Trying again...
```

_Originally posted by @LinqLover in https://github.com/josh-ashkinaze/Normalized-Google-Distance/issues/1#issuecomment-615401236_

**Comment by josh-ashkinaze** [comment]
Hey! Sorry for the late reply. Yeah I think Google blocked this from working :/
